version: "3.9"

services:
  # ==============================
  # ロードバランサ (Nginx)
  # ==============================
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-server
      - realtime-server
    networks:
      - app-net

  # ==============================
  # REST APIサーバー (2台構成)
  # ==============================
  api-server:
    build:
      context: ../api-server
      dockerfile: ../docker/api-server.Dockerfile
    deploy:
      replicas: 2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=db;Database=game;User=root;Password=root;
      - Redis__Host=redis
      - S3__ServiceUrl=http://minio:9000
      - S3__AccessKey=minio
      - S3__SecretKey=minio123
      - S3__BucketName=game-map
    depends_on:
      - db
      - redis
      - minio
    networks:
      - app-net

  # ==============================
  # MagicOnionサーバー (リアルタイム通信)
  # ==============================
  realtime-server:
    build:
      context: ../realtime-server
      dockerfile: ../docker/realtime-server.Dockerfile
    deploy:
      replicas: 2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__Host=redis
    depends_on:
      - redis
    networks:
      - app-net

  # ==============================
  # 日次バッチ (S3アップロード用)
  # ==============================
  daily-batch:
    build:
      context: ../daily-batch
      dockerfile: ../docker/daily-batch.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=db;Database=game;User=root;Password=root;
      - S3__ServiceUrl=http://minio:9000
      - S3__AccessKey=minio
      - S3__SecretKey=minio123
      - S3__BucketName=game-map
    depends_on:
      - db
      - minio
    networks:
      - app-net

  # ==============================
  # DB (MySQL)
  # ==============================
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-net

  # ==============================
  # Redis (Pub/Sub & セッション共有)
  # ==============================
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-net

  # ==============================
  # S3エミュレーター (MinIO)
  # ==============================
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - "9000:9000" # S3互換API
      - "9001:9001" # Webコンソール
    volumes:
      - ./minio/data:/data
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
