services:
  # ==============================
  # DB (MySQL)
  # ==============================
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: owdb
      MYSQL_USER: owuser
      MYSQL_PASSWORD: PassW0rd
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    networks:
      - app-net

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - app-net

  # ==============================
  # Redis (Pub/Sub & セッション共有)
  # ==============================
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-net

  # ==============================
  # S3エミュレーター (MinIO)
  # ==============================
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - "9000:9000"  # S3互換API
      - "9001:9001"  # 管理コンソール
    volumes:
      - minio_data:/data    
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
volumes:
  minio_data: